# Generated by Django 5.1.3 on 2024-12-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='Item_title_ar',
            field=models.CharField(default='Fresh Pear', max_length=100),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
