# Generated by Django 5.1.3 on 2024-12-06 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartorderitems_item_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
